### ISSUE TITLE
Save recordings offline?

### ISSUE THREAD

**Issue by PragTob** [asciinema/asciinema-cli#55]
I'd like to know if it's a desirable feature to save recordings offline - e.g. record console and then save the relevant files offline. They could then be used to play on websites other than asciinema.org (given an extracted player).

One of the problems with this so far is that the python script just does some basic recording. Then there is a whole lot of post processing going on in the asciinema.org webapp (Ruby).

I already extracted (and adjusted/unrailsified) the relevant ruby parts and implemented basic saving in the python script. You can see what I've done on the [save-files-locally branch of my fork](https://github.com/PragTob/asciinema/tree/save-files-locally).

Of course for this to be cool and sustainable the ruby post processing bits would have to go into a gem which can then be used by both offline people and the website could depend on it.

This together with an assets gem of the player (which is not too hard to extract) could enable people to record and show their own recordings without going through the website :)

I guess this somehow relates to #21 

What do you think?

Thanks for your awesome work on this technology!

**Comment by sickill** [comment]
It's implemented in #80.

**Comment by PragTob** [comment]
Well, then we can close this ;)

**Comment by sickill** [comment]
We have 1.0.0.rc1 with #80 merged: https://github.com/asciinema/asciinema-cli/releases/tag/v1.0.0.rc1
