### ISSUE TITLE
asciinema changes $PATH order.

### ISSUE THREAD

**Issue by introom** [asciinema/asciinema-cli#78]
I am using ZSH.
The asciinema version is: asciinema 0.9.9-0eee9b2

Suppose my path is: /Users/John/.dotfiles/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin

After I start asciinema, the path turns into:
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/Users/John/.dotfiles/bin:/usr/local/sbin

The change of order breaks many apps on my laptop.

**Comment by sickill** [comment]
asciinema doesn't mess `$PATH` in any way. You probably have some issue with your shell config files.
Try entering another zsh instance with `zsh` once you're in shell already. You will probably have the same result as with asciinema.

**Comment by introom** [comment]
It turns out Yosemite's shipped zsh doesn't work properly. More precisely, the /etc/zshenv is broken.

**Comment by kissgyorgy** [comment]
That was my issue either, I would have never solved this, thank you!
